name: Deploy StoryBook to GitHub Pages

on:
  push:
    branches:
      - 'master'

jobs:
  setup:
    name: Deploy StoryBook
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Deploying on GitHub Pages
        run: yarn run deploy-storybook --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
